### ISSUE TITLE
RSA Exemple

### ISSUE THREAD

**Issue by irineu** [GuillaumeBouchetEpitech/wasm-cryptopp-as-module#1]
Is there any example with RSA?

**Comment by irineu** [comment]
I've recompiled crypto++ in my machine and now is working perfectly

**Comment by GuillaumeBouchetEpitech** [comment]
just saw that, sorry, glad you managed it ;)

**Comment by GuillaumeBouchetEpitech** [comment]
@irineu 
that might help
=> https://github.com/GuillaumeBouchetEpitech/wasm-cryptopp-as-module/blob/main/tests/wasm/RSAFeatures.spec.ts
